[package]
name = "uaparser_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "uaparser_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
uaparser = "0.6.0"
lazy_static = "^1.4"
