[package]
name = "uaparser"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "uaparser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
uaparser-lib = { version = "0.5.1", package = "uaparser" }
